dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  sqflite:
  path:

description: Track your climbs

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=2.19.4 <4.0.0'

flutter:
  uses-material-design: true

name: climb
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1+1
